### PR TITLE
Use Genode VirtIO drivers for riscv_qemu machine.

### PR DESCRIPTION
**Pull request by tworaz**
I wanted to do it for a while, but never had the time. The nic driver switch is probably not that important, but the drivers interactive part allows a lot of existing, interactive Genode scenarios to be tested on RISC-V.

This patchset depends on https://github.com/genodelabs/genode/pull/4533.

### CODE REVIEW

**Comment by chelmuth** [comment]
Wouldn't it be more intuitive to move the virtio amendments into a `riscv:` entry in *repos/base/board/virt_qemu/qemu_args*. With your changes the opencores_nic driver is no longer tested in qemu.

**Comment by ssumpf** [comment]
> Wouldn't it be more intuitive to move the virtio amendments into a `riscv:` entry in _repos/base/board/virt_qemu/qemu_args_. With your changes the opencores_nic driver is no longer tested in qemu.

opencores_nic works only with Qemu patches on my laptop, solely used for MIG-V development, so I think it is okay to drop it.

**Comment by ssumpf** [comment]
@tworaz: Cool, I will test your changes as soon as possible.

**Comment by tworaz** [comment]
Making virt_qemu board from main Genode repository RISC-V aware is unfortunately not that trivial. For one there is a problem with image_link_address which right now can't have per architecture specific values. Then there is a matter of some board specific headers which are tied to ARM/ARM64 architecture. Its possible to provide solutions for those problems, but then once again we end up with riscv qemu specific files in main Genode repository from which they have been recently removed. In the end I've decided to just use existing riscv_qemu board and turn it into RISC-V version of virt_qemu. Not ideal, but less invasive.

**Comment by ssumpf** [comment]
@tworaz: Merged to staging and therefore to nightly testing. Thanks.

**Comment by ssumpf** [comment]
Included in Genode release 22.08.

**Pull request closed without merging**
